baseURL = 'https://www.mattb.nz/'
languageCode = 'en-nz'
title = 'Matt Brown'
theme = 'default'
rssLimit = 1

[build]
    writeStats = true

[permalinks]
    w = '/w/:year/:month/:day/:title'

[markup.goldmark.parser.attribute]
    block = true