baseURL = 'https://www.mattb.nz/'
languageCode = 'en-nz'
title = 'Matt Brown'
theme = 'default'
rssLimit = 4
enableRobotsTXT = true

[build]
    writeStats = true

[permalinks]
    w = '/w/:year/:month/:day/:title'

[markup.goldmark.parser.attribute]
    block = true

[markup.tableOfContents]
    startLevel = 2
    endLevel = 2
    ordered = false

[params]
    SubscribeUrl = "http://localhost:8080/"
    MetricsHost = "http://argon:8080/"
    connect = [
        { "title" = "Twitter", icon = "twitter.svg", "href" = "https://twitter.com/xleem" },
        { "title" = "Mastodon", icon = "mastodon.svg", "href" = "https://mastodon.nz/@mattb" },
        { "title" = "LinkedIn", icon = "linkedin.svg", "href" = "https://www.linkedin.com/in/mattbrown/" },
        { "title" = "GitHub", icon = "github.svg", "href" = "https://github.com/mattbnz" },
    ]

[params.images]
    alignment_start_class_name = "xl:float-left xl:mr-5"
    alignment_end_class_name = "xl:float-right xl:ml-5"
    class_name = "mx-auto"
    figure_class_name = "not-prose"
    figure_caption_class_name = "text-sm text-grey-800 mt-2"

[module]
[[module.imports]]
    path = 'github.com/hugomods/images'

[deployment]

[[deployment.targets]]
    name = 'gcs'
    URL = 'gs://mattbnz-site/'

[[deployment.targets]]
    name = 's3'
    URL = 's3://mattb.net.nz?region=us-east-1&profile=mkmba.nz-hugo'
		cloudFrontDistributionID = 'E7ZAULP0PDBKT'
