baseURL = 'https://www.mattb.nz/'
languageCode = 'en-nz'
title = 'Matt Brown'
theme = 'default'
rssLimit = 1
enableRobotsTXT = true

[build]
    writeStats = true

[permalinks]
    w = '/w/:year/:month/:day/:title'

[markup.goldmark.parser.attribute]
    block = true

[params]
    SubscribeUrl = "http://localhost:8080/"
    connect = [
        { "title" = "Twitter", icon = "twitter.svg", "href" = "https://twitter.com/xleem" },
        { "title" = "Mastodon", icon = "mastodon.svg", "href" = "https://mastodon.nz/@mattb" },
        { "title" = "LinkedIn", icon = "linkedin.svg", "href" = "https://www.linkedin.com/in/mattbrown/" },
        { "title" = "GitHub", icon = "github.svg", "href" = "https://github.com/mattbnz" },
    ]